---

- ec2_scaling_policy:
    profile: "{{ boto_profile | default(omit) }}"
    state: present
    name: "{{ item.name }}"
    region: "{{ wimpy_aws_region }}"
    adjustment_type: "{{ item.adjustment_type }}" # ChangeInCapacity | ExactCapacity | PercentChangeInCapacity
    asg_name: "{{ autoscaling.stack_outputs.AutoScalingGroup }}"
    scaling_adjustment: "{{ item.scaling_adjustment }}"
    min_adjustment_step: 1
    cooldown: "{{ item.cooldown }}"
  register: "sp_result"
  with_items: "{{ wimpy_scaling_policies }}"

- ec2_metric_alarm:
    profile: "{{ boto_profile | default(omit) }}"
    state: present
    region: "{{ wimpy_aws_region }}"
    name: "{{ item[0].name }}"
    metric: "{{ item[0].metric }}"
    namespace: "AWS/EC2"
    statistic: "{{ item[0].statistics }}"
    comparison: "{{ item[0].comparison }}"
    threshold: "{{ item[0].threshold }}"
    period: "{{ item[0].period }}"
    evaluation_periods: "{{ item[0].evaluation_periods }}"
    unit: "{{ item[0].unit }}"
    description: "{{ item[0].description }}"
    dimensions: "{{ item[0].dimensions }}"
    alarm_actions: "{{ item[1]['arn'] }}"
  when: "'{{item[1].name}}' == '{{item[0].scaling_policy_name}}'"
  with_nested:
    - wimpy_alarm_metrics
    - sp_result.results